### ISSUE TITLE
Array module - unit it is a dead end

### ISSUE THREAD

**Issue by jmagaram** [rescript-association/rescript-core#94]
I really like writing in pipeline style. And so when there is a function that ends with `unit`, like `sortInPlace` or `fillInPlaceToEnd`, it is quite annoying.
```
// x is unit, not what I want
let x = [43,7,99]->Array.map(i => i * 2)->Array.sortInPlace((a, b) => a - b)

// this works, annoying to write
let x2 = {
  let result = [43, 7, 99]->Array.map(i => i * 2)
  result->Array.sortInPlace((a, b) => a - b)
  result
}
```
Is there some reason why we can't almost **always return the new or mutated array**? If the name is ambiguous about what is happening, like `sort`, I agree returning `unit` makes things more clear what is going on. But if the name and function clearly indicates mutation, like `...inPlace`, it seems like there is no harm and it is quite convenient to return the modified item so you can continue with the pipeline. In some cases we can have both mutable and immutable versions, like `reverse` and `reverseInPlace` or `sort` and `sortInPlace` so the user doesn't have to do a copy.

**Comment by glennsl** [comment]
There's several reasons for this I think:

1. It would no longer be a zero-cost binding.
2. If a function returns a value that is not explicitly discarded, the compiler will emit a warning since 9 times out of 10 that indicates a bug in a functional language.
3. It would be likely to encourage confusing bugs. Mutation should be avoided, and making it very explicit that mutation happens both discourages its use for premature optimization and makes it easier to see where it happens. Inconvenience is a feature in this case, not a bug.

There should be immutable alternatives to all `InPlace` functions I think, and those should be preferred unless there's good reason to use mutating functions. In the few cases where there is good reason to use them you would probably not have a (large) pipeline anyway since functions such as `map` also does unnecessary allocation, and you'd likely want to do this kind of processing in an imperative loop.

**Comment by zth** [comment]
We've added a version of `sort` that returns a new array just for that case, but we haven't found it valuable to do the same for other APIs. Things like that is better suited to a standalone immutable array module, and that's outside of this project's scope.

**Comment by jmagaram** [comment]
Ok makes sense. Hadn't thought about the warning about discarded values and the zero cost of seeing the generated JavaScript look exactly like the JavaScript you would write other than that "Curry2" stuff! Glad to see a new sort function. I personally think most functions should have immutable flavors so you can do the pipeline and get the result you want.
